name = "AquaPore_Toolkit"
uuid = "63da81c1-80b0-4e17-94ee-0d2531a57af4"
authors = ["Joseph Alexander Paul POLLACCO", "Jesus GALVEZ_FERNANDEZ"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
